#ifndef UILOGINPLUG_GLOBAL_H
#define UILOGINPLUG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UILOGINPLUG_LIBRARY)
#  define UILOGINPLUGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UILOGINPLUGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UILOGINPLUG_GLOBAL_H
