//
// Created by cc on 18-12-17.
//

#ifndef QTALK_V2_OADEFINE_H
#define QTALK_V2_OADEFINE_H

namespace OA
{
    enum itemType
    {
        EM_ITEM_TYPE_APPROVALCENTERS,
        EM_ITEM_TYPE_ATTENDANCE,
        EM_ITEM_TYPE_BOARDROOM,
        EM_ITEM_TYPE_EXPENSEACCOUNT,
        EM_ITEM_TYPE_HR,
        EM_ITEM_TYPE_PERSONALCENTER,
        EM_ITEM_TYPE_QUNARIT,
        EM_ITEM_TYPE_TASK,
        EM_ITEM_TYPE_TOTAKEN,
        EM_ITEM_TYPE_WARRING,
        EM_ITEM_TYPE_WATCHER,
    };
}


#endif //QTALK_V2_OADEFINE_H
