#ifndef UINAVIGATIONPLUG_GLOBAL_H
#define UINAVIGATIONPLUG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UINAVIGATIONPLUG_LIBRARY)
#  define UINAVIGATIONPLUGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UINAVIGATIONPLUGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IUINAVIGATIONPLUG_GLOBAL_H
